#obj-$(CONFIG_ARCH_MSM8974) += htc_8974-panel.o

obj-$(CONFIG_MACH_BAGOSS) += htc_glu-panel.o
obj-$(CONFIG_MACH_GLU_U) += htc_glu-panel.o
obj-$(CONFIG_MACH_GLU_WLJ) += htc_glu-panel.o
obj-$(CONFIG_MACH_EYE_UL) += htc_eye-panel.o
